cmd/replicated/api.go
cmd/replicated/main.go

Silences usage for the `api` cli command since it currently makes reading errors more difficult. The message also gets logged twice currently, but cobra will handle that by default, so we don't need the extra print statement.
Before:
```
$ ./bin/replicated api --integration-license-id asdf --config-file /tmp/config.yaml
Error: only one of license in the config file or integration license id can be specified
Usage:
replicated api [flags]
Flags:
--config-file string              path to the replicated config file
-h, --help                            help for api
--integration-license-id string   the id of the license to use
--namespace string                the namespace where the sdk/application is installed
Global Flags:
--log-level string   set the log level (default "info")
only one of …
```

silence api cmd usage

---

pkg/appstate/ingress.go
pkg/appstate/ingress_test.go
pkg/k8sutil/clientset.go
pkg/k8sutil/clientset_test.go

add default-http-backend ingress service when k8s version is < 1.22
Fixes # https://app.shortcut.com/replicated/story/81855/app-status-not-showing-deployed-application-as-ready-even-if-the-app-is-running

add default-http-backend ingress service when k8s version is < 1.22

---

pkg/heartbeat/app.go
pkg/heartbeat/distribution.go
pkg/heartbeat/distribution_test.go
pkg/heartbeat/types/types.go
pkg/k8sutil/clientset.go

https://app.shortcut.com/replicated/story/82294/sdk-install-shows-gke-autopilot-for-non-autopilot-cluster
This check doesn't work as intended.  It checks for the presence of an `auto.gke.io` resource group, but both standard and autopilot clusters can have this.  The proposal for now is to just remove the standard vs autopilot distinction and call them both GKE.

remove gke autopilot distro check

---

.github/workflows/publish.yaml

[SC-78133](https://app.shortcut.com/replicated/story/78133/automate-release-note-creation-as-a-pr-in-the-docs-repo)
This PR adds the `generate-release-notes-pr` job to the release workflow so that it triggers the `replicated-sdk-release-notes` workflow in the replicated-docs repo. The workflow will open a PR to update the release notes during the release of a new version of the replicated sdk.
Related PR in replicated-docs: https://github.com/replicatedhq/replicated-docs/pull/1338

generate release notes PR on release

---

.github/workflows/main.yaml
Dockerfile

These PR changes the Docker Image from the standard golang to use Chainguard's community golang image for the first build stage and Chainguard's static image for the final build stage.
- The current golang image on dockerhub contains 66 vulnerabilities and is 792MB.
- The Chainguard image image contains 0 vulnerabilities and is 652MB.
- Using Chainguard means we are using an image with fewer vulnerabilities and a smaller attack surface.
- Using the static image for the final build stage reduced the total image size from 894MB to 49.9MB
- Use chainguard go:1.20 for first stage and chainguard static:latest for final stage
- Add a `build-and-push-ttl-image` to validate the image build on PR

Use Chainguard Image for Replicated SDK

---

.github/workflows/publish.yaml

- passes the previous tag in the repo to the release notes generator to use as the base.

pass previous tag as base to release notes generator

---

Dockerfile

Fixes https://github.com/replicatedhq/replicated-sdk/issues/66
Migration guide: https://www.chainguard.dev/unchained/a-guide-on-how-to-use-chainguard-images-for-public-catalog-tier-users

use wolfi-base to install go 1.20

---

chart/templates/_helpers.tpl
chart/templates/replicated-sdk-deployment.yaml
chart/values.yaml.tmpl

Adds support for OpenShift clusters. OpenShift requires the user/group IDs to fall within the dynamically generated range that's assigned to the namespace after creation. Since it's difficult to know that at installation time, OpenShift automatically assigns a user ID if it's not specified.
This PR adds functionality to detect if the cluster is OpenShift, and omits the `runAsUser` and `runAsGroup` fields from the `podSecurityContext` so that OpenShift can dynamically/automatically assign the user ID.
Also, OpenShift applies the `restricted-v2` security context constraints by default, which requires containers to:
- Run as non-root.
- Have a read-only root filesystem.
- Disable privilege escalation.
- Drop all OS capabilities.
- Use `RuntimeDefault` as the `seccompProfile`.
And this PR …

Add support for OpenShift clusters

---

.github/workflows/main.yaml

Fixes: https://github.com/replicatedhq/replicated-sdk/actions/runs/5967728367/workflow
`head_ref` is only defined on pull requests. This PR adds changes to fallback to the `run_id` when `head_ref` is not defined (e.g. when running the workflow on the `main` branch). It also prefixes the concurrency group with `${{ github.workflow }}-` so that only (previous) jobs from that particular workflow get cancelled.
References:
- https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
- https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
Fixes #
```release-note
NONE
```
NONE

fix running CI in main

---

pact/custom_metrics_test.go
pkg/apiserver/server.go
pkg/handlers/custom_metrics.go
pkg/handlers/custom_metrics_test.go
pkg/metrics/metrics.go

https://app.shortcut.com/replicated/story/85778/endpoint-in-kots-to-receive-dispatch-custom-metrics-to-replicated-app
This add an API endpoint for application to report custom metrics.  The metrics payload is a flat json object where each key is a scalar value.  Data is forwarded to replicated.app synchronously.
replicated.app endpoint does not yet exist and will be updated before this PR is merged.
Fixes #
```release-note
* Adds replicated-sdk API to send custom application metrics to replicated.app service
```
Yes, TODO.

API to accept metrics from application

---

.github/actions/validate-endpoints/action.yml
.github/workflows/main.yaml
chart/templates/_helpers.tpl
chart/templates/replicated-sdk-configmap.yaml
chart/templates/replicated-sdk-deployment.yaml
chart/templates/replicated-sdk-role.yaml
chart/templates/replicated-sdk-rolebinding.yaml
chart/templates/replicated-sdk-secret.yaml
chart/templates/replicated-sdk-service.yaml
chart/templates/replicated-sdk-serviceaccount.yaml
chart/templates/replicated-sdk-supportbundle.yaml
chart/values.yaml.tmpl
pact/heartbeat_test.go
pact/license_test.go
pkg/apiserver/bootstrap.go
pkg/appstate/operator.go
pkg/handlers/app.go
pkg/heartbeat/app.go
pkg/heartbeat/heartbeat.go
pkg/heartbeat/util.go
pkg/heartbeat/util_test.go
pkg/helm/helm.go
pkg/k8sutil/fake.go
pkg/util/env.go
pkg/util/replicated.go

Makes the chart/api work with helm template + kubectl. Uses the deployment's UID as both Replicated and app ID instead of generating new IDs during templating. Will keep using existing IDs for existing installations from the ConfigMap as to not introduce a breaking change. ConfigMap will not be created for fresh installations going forward.
Fixes #
```release-note
Adds support for installing the Helm chart via `helm template` then `kubectl apply` the generated manifests.
```
TBD

Make the chart/api work with helm template + kubectl

---

pact/custom_metrics_test.go

Test added in https://github.com/replicatedhq/replicated-sdk/pull/79 has missing headers which make the request fail.
Error:
```
[35mreplicated-app_1  |[0m [31m[2023-09-01T19:03:10.571] [ERROR] [TSED] - [39m{
[35mreplicated-app_1  |[0m   method: 'POST',
[35mreplicated-app_1  |[0m   url: '/application/custom-metrics',
[35mreplicated-app_1  |[0m   headers: {
[35mreplicated-app_1  |[0m     version: 'HTTP/1.0',
[35mreplicated-app_1  |[0m     cookie: '',
[35mreplicated-app_1  |[0m     'x-forwarded-for': '127.0.0.1',
[35mreplicated-app_1  |[0m     authorization: 'Basic c2RrLWxpY2Vuc2UtY3VzdG9tZXItMC1saWNlbnNlOnNkay1saWNlbnNlLWN1c3RvbWVyLTAtbGljZW5zZQ==',
[35mreplicated-app_1  |[0m     'user-agent': 'Replicated-SDK/v0.0.0-unknown',
[35mreplicated-app_1  |[0m     host: …
```

Add missing request headers

---

chart/templates/_helpers.tpl
chart/templates/replicated-configmap.yaml
chart/templates/replicated-deployment.yaml
pkg/util/replicated.go

Fixes an issue where the ConfigMap gets deleted even when upgrading from an older installation that still uses the `replicated-sdk` ConfigMap to store the instance IDs.
Fixes #
```release-note
NONE
```
NONE

Lookup the dynamic configmap name instead of 'replicated'

---

pact/custom_metrics_test.go
pkg/handlers/custom_metrics.go

Removing requirement for authorization header since this only introduces an extra step for apps that don't have license ID.
Fixes #
```release-note
- Custom metrics API no longer requires authorization header.
```
https://github.com/replicatedhq/replicated-docs/pull/1441

Remove authorization header from custom metrics API

---

chart/templates/replicated-supportbundle.yaml

Collects [app info](https://docs.replicated.com/reference/replicated-sdk-apis#get-appinfo) and [license info](https://docs.replicated.com/reference/replicated-sdk-apis#get-licenseinfo) from a running replicated sdk service and stores the information in a support bundle. An analyser has been added to warn whenever the `"appStatus"` is not `"ready"`
You can run `kubectl support-bundle --load-cluster-specs` against a cluster with the service to generate the support bundle
Fixes #
```release-note
```

chore: Add replicated app info collector and analyser

---

pkg/apiserver/bootstrap.go
pkg/appstate/util.go
pkg/appstate/util_test.go

Ignores empty documents when generating status informers so that the API comes up without any issues.
Fixes #
```release-note
- Fixes an issue where the `replicated` Pod/API failed to come up due to the inability to generate status informers if the application contains empty YAML documents, or documents that only have comments.
```
NONE

Ignore empty documents when generating status informers

---

.github/actions/validate-endpoints/action.yml
.github/workflows/main.yaml
chart/templates/replicated-deployment.yaml

This PR adds an annotation to the pod spec with the checksum of the `replicated-secret` template to ensure that it's restarted on updates to the configuration.
https://app.shortcut.com/replicated/story/90562/instance-insights-app-version-should-update-when-the-chart-is-upgraded
```release-note
Fixes an issue where data returned from API endpoints and instance reporting was outdated after a chart was upgraded
```
NONE

add checksum annotation for replicated-secret

---

.github/workflows/main.yaml
chart/templates/replicated-deployment.yaml
chart/values.yaml.tmpl

PR from fork: https://github.com/replicatedhq/replicated-sdk/pull/95
Provide the ability to add extra env variables to the replicated-sdk deployment.
Add the following snippet to the helm value file.
```
extraEnv: 
- name: TEST
value: 123
```
Run `helm template repli .  --dry-run --debug -f values.yaml.tmpl` and you should see the value added in the replicated-deployment env.
```release-note
Adds support for adding additional environment variables to the replicated deployment via the `extraEnv` value.
```
NONE

Add extra env to helm template

---

.github/workflows/main.yaml

This PR disables go module caching for the `make tests` job because this can cause pact tests not to execute. Caching is enabled by default in `actions/setup-go@v4`, whereas it was not in `v3`.  This can cause failures like the following: https://github.com/replicatedhq/replicated-sdk/actions/runs/6422456432/job/17438965650#step:5:276
Fixes #
```release-note
```

fix pact testing cache in ci

---

.github/workflows/main.yaml
chart/templates/replicated-deployment.yaml
chart/values.yaml.tmpl

Originally from: https://github.com/replicatedhq/replicated-sdk/pull/103
Adds support for configuring custom tolerations on the SDK deployment.
Fixes #
```release-note
Adds support for adding custom tolerations to the SDK deployment via the `tolerations` value.
```
https://github.com/replicatedhq/replicated-docs/pull/1528

feat: allow a user to define tolerations (e.g. multi arch clusters, specific nodes, etc)

---

.github/workflows/main.yaml
chart/templates/replicated-secret.yaml
chart/values.yaml.tmpl
pkg/apiserver/bootstrap.go
pkg/appstate/util.go

This PR allows an empty array of status informers to be explicitly passed to the SDK. Previously if this was the case, the SDK would automatically generate status informers based on the Helm release. The default value for `statusInformers` will still result in them being automatically generated, which maintains existing behavior.
Part of https://app.shortcut.com/replicated/story/88171/detect-and-configure-the-replicated-sdk-chart-subchart-if-it-s-part-of-the-vendor-s-application
```release-note
Status informers will no longer be automatically generated if the user explicitly passes an empty array for the `statusInformers` value.
```
NONE

allow empty status informers

---

pkg/apiserver/bootstrap.go
pkg/appstate/operator.go
pkg/heartbeat/app.go
pkg/heartbeat/util.go
pkg/heartbeat/util_test.go
pkg/store/memory_store.go
pkg/upstream/replicated.go

When the `replicated` pod restarts, it fetches/sends information to replicated.app while bootstrapping, and it wouldn't have calculated the state of the application yet. We should only send app status related information only if it's been initialized. This is also possible now that our SaaS services support processing partial telemetry data.
Fixes #
```release-note
NONE
```
NONE

Send app status related info only if initialized

---

.github/actions/validate-endpoints/action.yml
pkg/apiserver/server.go
pkg/handlers/app.go

This PR removes the `/api/v1/app/metrics` endpoint added in https://github.com/replicatedhq/replicated-sdk/pull/101
https://app.shortcut.com/replicated/story/90703/partial-revert-add-an-endpoint-to-the-sdk-where-metrics-can-be-retrieved-adhoc
```release-note
```

remove app metrics endpoint

---

.github/workflows/daily-scan.yaml
.github/workflows/publish.yaml
Makefile
chart/values.yaml.tmpl

Uses dockerhub to host the replicated-sdk image instead of ghcr.io and renames the image from `replicated` to `replicated-sdk`
Fixes part of [SC-89414](https://app.shortcut.com/replicated/story/89414/ability-for-the-sdk-api-to-handle-being-installed-in-a-kots-airgap-scenario)
```release-note
NONE
```
NONE

use dockerhub instead of ghcr.io and rename image to replicated-sdk

---

chart/templates/replicated-deployment.yaml
chart/values.yaml.tmpl

Since the image was renamed to `replicated-sdk`, it would make more sense the Helm value is named as such.
Fixes #
```release-note
- Renames the `images.replicated` Helm value to `images.replicated-sdk`.
```
NONE

images.replicated-sdk instead of images.replicated

---

.github/actions/validate-endpoints/action.yml

Adds a `namespace` input to the `validate-endpoints` GH action to specify the namespace that the Replicated SDK is deployed to. Defaults to `default`.
Fixes #
```release-note
```

add namespace input to validate-endpoints action

---

chart/templates/replicated-deployment.yaml
chart/values.yaml.tmpl

This PR adds default values for `fsGroup` and `supplementalGroups` to the SDK pod security context. The goal is to provide more out-of-the-box support for admission controllers that may require these fields be set.
Fixes #
```release-note
Adds `fsGroup` and `supplementalGroups` to the default PodSecurityContext for the Replicated SDK deployment.
```
NONE

add default fsGroup and supplementalGroups to podSecurityContext

---

.github/actions/build-push-action/action.yml
.github/workflows/publish.yaml

This PR adds SLSA generation for the replicated SDK image.
Supply-chain Levels for Software Artifacts, or SLSA ("salsa").
Fixes # No related issues in the github issue tracker
This uses the reussable workflow from slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.10.0
N/A
```release-note
Adds SLSA generation for the replicated SDK image. SLSA is the Supply-chain Levels for Software Artifacts ( Pronounced "salsa").
For example, you will be able to validate the attestation via
cosign download attestation replicated/replicated-sdk:VERSION | jq -r .payload | base64 -d | jq
or
search Sigstor using Rekor at https://search.sigstore.dev/
```
Yes

Adds SLSA generation at the end of the publish workflow

---

chart/templates/replicated-supportbundle.yaml

Quotes the namespaces defined in the support bundle secret. This also helps get rid of the following warnings from the linter in the vendor portal:
Fixes #
```release-note
* Fixes an issue where the namespace fields in the support bundle spec were not quoted, which caused the linter to show schema warnings.
```
NONE

Quote namespaces in the support bundle spec

---

.github/workflows/main.yaml
chart/templates/replicated-supportbundle.yaml

This PR adds the deployed namespace in the logs collector that is part of the Replicated SDK support bundle. This fixes an issue where the logs may fail to collect in environments with namespace-restricted RBAC.
Fixes #
```release-note
Fixes an issue where the replicated pod logs collector could fail in environments with namespace-restricted RBAC
```

specify namespace in logs collector

---

.github/workflows/main.yaml
chart/templates/replicated-supportbundle.yaml
pkg/handlers/app.go
pkg/handlers/license.go

- Remove `http` collectors (they were not working)
- Uses exec collectors via `curl`
- Updates `/license/info` and `/app/info` SDK endpoints to return additional details
Fixes #
```release-note
- Returns additional license-info and app-info details on respective SDK HTTP endpoints.  
- Support bundle spec updated to extract license, app, history, and release information via an exec collector.  
```
Notice the new `replicated-app*` exec folders

Use exec collectors instead of http for support bundles

---

pkg/k8sutil/clientset.go
pkg/k8sutil/clientset_test.go

Story details: https://app.shortcut.com/replicated/story/109535

fix: [sc-109535] k8s minor version parsing error

---

chart/templates/replicated-deployment.yaml
chart/values.yaml.tmpl

This adds support for specifying additional Certificate Authorities that can be used for adding private CAs when deploying behind a proxy.
Fixes https://app.shortcut.com/replicated/story/98357/use-a-custom-certificate-authority-with-replicated-sdk
Relevant docs PR: https://github.com/replicatedhq/replicated-docs/pull/2667
```release-note
Adds support for custom Certificate Authorities.
```

Allow specifying custom Certificate Authority as a ConfigMap name

---

.github/workflows/publish.yaml

Use listReleases instead of listTags when looking for latest release because tags are sorted alphabetically and releases are sorted chronologically.
Fixes https://app.shortcut.com/replicated/story/109223/do-not-put-a-v-prefix-on-sdk-versions-in-github
```release-note
```

Use listReleases instead of listTags

---

Makefile
chart/templates/replicated-deployment.yaml
chart/values.yaml.tmpl

In addition to using a configmap to provide SDK with custom CA, this allows using a secret.  Example values:
```
privateCASecret:
name: additional-ca
key: custom-ca.crt
```
This is a follow up to https://github.com/replicatedhq/replicated-sdk/pull/209
Fixes https://app.shortcut.com/replicated/story/113584/can-t-reuse-existing-secret-for-custom-ca
```release-note
Adds support for specifying custom Certificate Authorities using a secret.
```
https://github.com/replicatedhq/replicated-docs/pull/2742

Ability to specify additional CA using a secret name/key

---

chart/templates/replicated-clusterrolebinding.yaml
chart/templates/replicated-role.yaml
chart/values.yaml.tmpl

Allows specifying ClusterRole name to use for the service account that will be created for Replicated SDK.
Relevant KOTS PR: https://github.com/replicatedhq/kots/pull/4952
Fixes https://app.shortcut.com/replicated/story/114128/replicated-sdk-reports-k0s-when-installed-in-embedded-cluster-causing-distribution-to-flip-flop-in-events-view
```release-note
* Adds support for specifying ClusterRole for Replicated SDK RBAC.
```

Allow specifying ClusterRole when deploying Replicated SDK

---

deploy/apko.yaml.tmpl
deploy/melange.yaml.tmpl
pkg/meta/latest_custom_metrics.go
pkg/meta/meta.go

If metadata secret becomes malformed, reporting custom metrics will start failing and will not recover on its own. When the secret or the data are malformed, the API should continue to function.
Fixes https://app.shortcut.com/replicated/story/117030/replicated-sdk-fails-to-report-custom-metrics-if-the-latest-custom-metrics-key-is-not-there
```release-note
Fixes a bug that could cause custom metrics to not be reported.
```
NONE

Handle bad metadata secret values gracefully

---

pkg/appstate/ingress.go
pkg/appstate/ingress_test.go

When application includes an Ingress, without a LoadBalancer ingress will not have an address associated with it. While this can be a valid setup, it will always result in application as being unavailable.
Fixes https://app.shortcut.com/replicated/story/113505/sdk-falsely-reporting-ingress-as-unavailable-when-it-should-not
```release-note
Fixes a bug that could result in instance being reported as unavailable if application includes an Ingress resource.
```

Ingress will only have an IP address when type is LoadBalancer

---

.github/workflows/daily-scan.yaml
.github/workflows/main.yaml

Chainguard build is failing with the following error
> Error: failed to build image components: building "amd64" layer: installing apk packages: error getting package dependencies: constraining initial packages: parsing constraint "replicated=4d93cd4ad22f51ee8e710da091a96aa7a798e038-r0": invalid version 4d93cd4ad22f51ee8e710da091a96aa7a798e038-r0, could not parse
Fixes #
```release-note
```

Try a valid semver for melange package version

---

.github/workflows/main.yaml
chart/templates/replicated-deployment.yaml
chart/values.yaml.tmpl

Allow setting `affinity` on replicated deployment, similar to `tolerations`
Fixes https://app.shortcut.com/replicated/story/102275/replicated-sdk-chart-should-support-configuring-node-affinity-rules
```release-note
Adds support for setting `affinity` for Replicated SDK deployment
```
https://github.com/replicatedhq/replicated-docs/pull/2906

Allow setting affinity for replicated deployment

---

pkg/handlers/app.go
pkg/handlers/handlers.go
pkg/integration/data/default_mock_data.yaml
pkg/integration/data/test_mock_data_v2.yaml
pkg/integration/mock_test.go
pkg/integration/types/types.go

Add better indicators for mock data:
- Remove real channel/release info from `/app/info` endpoint and replace it with mock data for consistency
- Add `X-Replicated-Mock-Data: true` header to responses when mock data is used.
- Add "mock" to text fields to indicate that data is not real.
Fixes https://app.shortcut.com/replicated/story/100946/integration-mode-is-messy-for-the-sdk-developer-experience-improve-sdk-integration-experience-as-part-of-calling-it-ga
```release-note
- Adds support for mocking channelID, channelName, channelSequence, releaseSequence in current release info returned by /app/info API.
```

Mock all release data without mixing with real data

---

deploy/melange.yaml.tmpl

Tagged release failed with the error
> Error: failed to build image components: building "amd64" layer: installing apk packages: error getting package dependencies: constraining initial packages: parsing constraint "replicated=1.0.0-beta.33-r0": invalid version 1.0.0-beta.33-r0, could not parse
2024/12/23 22:28:09 INFO error during command execution: failed to build image components: building "amd64" layer: installing apk packages: error getting package dependencies: constraining initial packages: parsing constraint "replicated=1.0.0-beta.33-r0": invalid version 1.0.0-beta.33-r0, could not parse
Fixes #
```release-note
```

Hardcode version for melange config

---

.github/actions/cmx-versions/.gitignore
.github/actions/cmx-versions/action.yaml
.github/actions/cmx-versions/dist/index.js
.github/actions/cmx-versions/index.js
.github/actions/cmx-versions/package-lock.json
.github/actions/cmx-versions/package.json
.github/workflows/main.yaml

Use whatever latest k8s version is available on CMX to run e2e tests.
Fixes https://app.shortcut.com/replicated/story/89800/update-sdk-cmx-testing-to-benefit-from-recent-kots-work-to-inherit-new-cmx-distros
```release-note
```

Detect cluster versions supported by CMX

---

chart/templates/_helpers.tpl
chart/templates/replicated-deployment.yaml
chart/values.yaml.tmpl

This PR adds support for custom labels in the Helm chart. It introduces two new values:
- `commonLabels`: Allows adding custom labels to all resources created by the chart
- `podLabels`: Allows adding pod-specific labels only to the pod template
Additionally, it introduces a generic helper function `replicated.mergeValues` that can be used to merge multiple maps, making the chart more maintainable and providing a reusable function for future needs.
Fixes #
The PR introduces a new generic merge helper that could be useful for other parts of the chart in the future. We're currently using it to merge common labels with pod-specific labels in the deployment template.
To test the new label functionality:
1. Install the chart with custom labels:
```yaml
commonLabels:
environment: production …
```

feat: add ability to pass custom labels

---

.github/workflows/daily-scan.yaml

Since the [switch to chainguard](https://github.com/replicatedhq/replicated-sdk/commit/16b22c2ab0621597fbdbbdf9ef8fc835e294fb8e#diff-2668ebb199a46c01733d0e145f741a3183dc211c98fe515e1952bf6e19522096L37), daily_scan job has been failing with
> Error: publishing images from index: POST https://index.docker.io/v2/replicated/replicated-sdk/blobs/uploads/: UNAUTHORIZED: authentication required; 
This will use ttl.sh, similar to [e2e tests](https://github.com/replicatedhq/replicated-sdk/blob/45d91c230abb34a6be1465556821980216056fd1/.github/workflows/main.yaml#L59).
Fixes #
```release-note
```

Use ttl.sh for daily scans

---

.github/workflows/daily-scan.yaml

Modifies the security scanning strategy to scan the actual published image from DockerHub instead of rebuilding and scanning a fresh image.
Previously, the scan would rebuild the image using the latest dependencies from Chainguard/apko, which meant we were scanning a potential future release rather than our current production release. This defeated the purpose of detecting new vulnerabilities in our published image.
The new workflow:
- Gets the latest release tag
- Scans that specific published image directly from DockerHub
- Reports findings to GitHub Security tab
- This change ensures we detect new CVEs that affect our users' currently deployed version, rather than scanning a fresh build with updated dependencies.
Fixes #
- The workflow runs daily at midnight UTC
- Uses minimal …

Scan the most recent release for CVEs

---

.github/workflows/daily-container-scans.yml
.github/workflows/scan-container-image.yml

New workflows for scanning using grype and our custom sarif additions for internal tracking
Fixes # NONE
Current daily scans using Trivy proved to be a problem when attempting to add metadata to the sarif report required for metadata tracking. Trivy was having a hard time with escaping some data, generating valid sarif and adding custom fields, even though the sarif format supports it. I did a test with Grype and determined it was able to do what I needed and also tends to be a better scanner overall.
```release-note
NONE
```
NONE

init new workflows for scanning using grype and custom sarif additions

---

.github/workflows/publish.yml
dagger/chainguard.go

This adds QEMU to the runner so that it can cross compile (surprise requirement)
This uses a larger runner so it's quicker.
Then, the dagger-for-github caches creds. I've tried everything i can think of to reset these. It's passing the right creds, but publishing to staging and then prod in a single job always results in the 2nd publish 401.  Thie APKO step or dagger is caching that credential. 
To make this more reliable, split staging and prod into two steps. This does create 2 separate melange builds, but ultimately since they run in parallel, it actually results in a faster pipeline.

Fix cross compile in action runner

---

go.mod
go.sum

fixes https://github.com/replicatedhq/replicated-sdk/security/dependabot/31- updating github.com/containerd/containerd from v1.7.24 to v1.7.27 
fixes https://github.com/replicatedhq/replicated-sdk/security/dependabot/35 - update golang.org/x/net from v0.37.0 to v0.38.0 
```release-note
```

Bump golang.org/x/net and github.com/containerd/containerd

---

.github/workflows/slsa.yml
dagger/publish.go

The slsa workflow was being triggered by dagger on a tag being cut, however, it would exit immediately and perform  no work because it was expecting to have been executed as part of a larger actions workflow. It was looking for a `needs.package-and-publish-production.result` from a previous step run. 
I updated dagger to supply a bool to signal whether this is a staging/production run as a replacement.
```release-note
```

Fix slsa workflow execution

---

dagger/chainguard.go

Uses the apko image digest, rather than id - as the actual digest. 
```release-note
```

Use actual image digest - as digest

---

dagger/e2e.go

This increases the timeout for the 'validate' CI run's creation of k8s clusters, allowing it to complete succesfully.
```release-note
```

Fix 'validate' CI run
