replicatedhq/replicated-sdk

pact/license_test.go
This PR adds pacts for the replicated sdk license sync
Fixes #
Run `make test-pact`
```release-note
NONE
```
NONE
=> add license sync pacts

.github/workflows/publish.yaml, Makefile
* Records releases to both staging and production environments to ensure versions are tested correctly
* Maintains only one supported release (up for discussion, but may be appropriate for the current beta state)
Fixes #
```release-note
NONE
```
NONE
=> add record support ended, add record release to staging

pkg/handlers/custom_metrics.go, pkg/handlers/custom_metrics_test.go
This PR fixes in nil pointer panic in custom metrics handler.
Fixes #
```release-note
Fixes a bug that caused no status code to be returned from the custom metrics API requests.
```
NONE
=> Don't panic on nil values

.github/workflows/main.yaml, chart/templates/replicated-deployment.yaml, chart/values.yaml.tmpl, pact/license_test.go, pkg/buildversion/buildversion.go
Removes the ability to configure user agent.
Fixes #
```release-note
NONE
```
NONE
=> UserAgent should not be configurable

.github/workflows/main.yaml
Published pacts in this workflow aren't recorded to staging/prod, so they're not even used.
Fixes #
```release-note
NONE
```
NONE
=> Don't publish pact on PR or merge to main

.github/actions/validate-endpoints/action.yml, .github/workflows/main.yaml, pkg/handlers/app.go
Make sure the API can run in airgapped mode and does not try to reach out to the internet.
Fixes #
```release-note
NONE
```
NONE
=> Ability for the SDK API to handle being installed in a KOTS airgap scenario

pkg/heartbeat/app.go
Fixes an issue where in rare scenarios, telemetry events that closely followed each other were reported out of order.
Fixes [SC-91640](https://app.shortcut.com/replicated/story/91640/race-condition-when-kots-and-the-sdk-report-initial-app-status)
```release-note
Fixes an issue where in rare scenarios, telemetry events that closely followed each other were reported out of order.
```
NONE
=> Handle race condition where events are reported out of order

pkg/license/license.go
Sends instance metadata whenever SDK checks for license. 
Fixes #
```release-note
NONE
```
NONE
=> Update license reporting

.github/workflows/main.yaml
Updates the versions of Kubernetes we test on using CMX.
Fixes #
```release-note
NONE
```
NONE
=> Update Kubernetes versions we test on

pkg/license/license.go, pkg/report/custom_app_metrics.go, pkg/report/instance.go, pkg/upstream/replicated.go, pkg/util/http.go
- Sets a 10 second timeout for http client
Fixes #
```release-note
NONE
```
Nope
=> Add default timeout for HTTP client

pact/license_test.go
adding an array of channels to this license, need to merge this for CI to update the pact broker and then re-enable
=> Channels pact

pkg/report/distribution.go, pkg/report/distribution_test.go, pkg/report/types/types.go
Fixes https://app.shortcut.com/replicated/story/110105/sdk-doesn-t-detect-ec-distro
```release-note
```
=> Detect embedded-cluster distribution for reporting

.github/workflows/main.yaml, .github/workflows/publish.yaml, chart/templates/_helpers.tpl, chart/templates/replicated-deployment.yaml, chart/values.yaml.tmpl
Currently, the image name is derived from a single helm value. This doesn't leave any flexibility if the registry needs to be overwritten, but all other properties of the image should be sourced from the defaults in the chart
Fixes #
```release-note
```
=> feat: template helm image properties

.github/workflows/publish.yaml
Just use ref_name as current tag value. No tricks.
=> Use ref_name as current tag value

.github/workflows/main.yaml
Fixing tests
Fixes #
```release-note
```
=> Enable dev mode for the license in e2e tests

.gitignore, chart/templates/_helpers.tpl, chart/templates/replicated-secret.yaml, chart/values.yaml.tmpl
=> Add new value to configure replicated app service domain

chart/templates/replicated-deployment.yaml, chart/values.yaml.tmpl
=> feat: allow nodeselector to be set for replicated sdk

.github/actions/generate-support-bundle/action.yml, .github/workflows/main.yaml
See - https://github.com/actions/runner-images/issues/11101
Fixes #
```release-note
```
=> Update cmx_versions action to use Ubuntu 22.04 to avoid brownouts

.github/workflows/publish.yml, dagger/publish.go
Create a release when production is called from GHA
=> push a release when finished

chart/templates/replicated-deployment.yaml, chart/values.yaml
This PR adds `livenessProbe` configuration support to the Replicated SDK Helm chart, mirroring the existing `readinessProbe` implementation. Users can now configure liveness probes with flexible YAML configuration and automatic TLS scheme detection.
- Added `livenessProbe: ~` configuration option
- Included comprehensive documentation with example configuration
- No default values provided (as requested) - users must explicitly configure if needed
- Added comments explaining the difference between liveness and readiness probes
- Added conditional `livenessProbe` block in container specification
- Implemented `toYaml` rendering for flexible configuration
- Added automatic HTTPS scheme detection when `tlsCertSecretName` is present
- Follows identical pattern to existing `readinessProbe` …
=> Add livenessProbe support to Helm chart

chart/templates/replicated-role.yaml, dagger/e2e.go, test-chart/templates/second-deployment.yaml
This creates a limited but general role for minimalRBAC if the user does not specify statusInformers.
```release-note
```
=> allow specifying no statusinformers with minimal RBAC
